version: '3.8'

services:
    nginx:
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./wordpress:/wordpress
        - ./site.conf:/etc/nginx/conf.d/default.conf
      networks:
        - wordpress-network
    php:
      image: php:fpm
      restart: always
      volumes:
        - ./wordpress:/wordpress
      networks:
        - wordpress-network
    mysql:
      image: mysql:latest
      restart: unless-stopped
      command: --authentication_policy=mysql_native_password
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      volumes:
        - my-db:/var/lib/mysql
      ports:
        - '3306:3306'
      networks:
        - wordpress-network
networks:
  wordpress-network:
    driver: bridge

volumes: # add persistent data even if container is removed.
  my-db:
